services:
    Zeggriim\RiotApiDataDragon\RiotApiDataDragon:
        autowire: true
        public: false

    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\ChampionApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\ItemApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\LanguageApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\ProfileIconApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\SummonerApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\VersionApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\ChampionApiInterface: '@Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\ChampionApi'
    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\ItemApiInterface: '@Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\ItemApi'
    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\LanguageApiInterface: '@Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\LanguageApi'
    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\ProfileIconApiInterface: '@Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\ProfileIconApi'
    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\SummonerApiInterface: '@Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\SummonerApi'
    Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\VersionApiInterface: '@Zeggriim\RiotApiDataDragon\Endpoint\DataDragon\VersionApi'


    Zeggriim\RiotApiDataDragon\RiotApiDataLeague:
        autowire: true
        public: false
        arguments:
            $apikey: '%env(string:API_RIOT_KEY)%'

    Zeggriim\RiotApiDataDragon\Endpoint\DataLeague\LeagueApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\Endpoint\DataLeague\LeagueApiInterface: '@Zeggriim\RiotApiDataDragon\Endpoint\DataLeague\LeagueApi'
