services:
    Zeggriim\RiotApiDataDragon\RiotApiDataLeagueClient:
        autowire: true
        public: false
        arguments:
            $apiKey: '%env(string:API_RIOT_KEY)%'


    # Endpoint Data Dragon
    Zeggriim\RiotApiDataDragon\RiotApiDataDragonClient:
        autowire: true
        public: false

    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\ChampionApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\ItemApi:
        autowire: true
        arguments:
            $denormalizer: '@serializer'

    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\LanguageApi:
        autowire: true
        arguments:
            $denormalizer: '@serializer'

    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\ProfileIconApi:
        autowire: true
        arguments:
            $denormalizer: '@serializer'

    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\SummonerApi:
        autowire: true
        arguments:
            $denormalizer: '@serializer'

    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\VersionApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\DataDragon\DataDragonApi:
        autowire: true
        public: false

    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\ChampionApiInterface: '@Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\ChampionApi'
    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\ItemApiInterface: '@Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\ItemApi'
    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\LanguageApiInterface: '@Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\LanguageApi'
    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\ProfileIconApiInterface: '@Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\ProfileIconApi'
    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\SummonerApiInterface: '@Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\SummonerApi'
    Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\VersionApiInterface: '@Zeggriim\RiotApiDataDragon\DataDragon\Endpoint\VersionApi'
    Zeggriim\RiotApiDataDragon\DataDragon\DataDragonApiInterface: '@Zeggriim\RiotApiDataDragon\DataDragon\DataDragonApi'

    # Endpoint Data League
    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\AccountApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\ChampionApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\ChampionMasteryApi:
        autowire: true
        arguments:
            $denormalizer: '@serializer'

    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\LeagueApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\MatchApi:
        autowire: true

    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\SummonerApi:
        autowire: true
        arguments:
            $denormalizer: '@serializer'

    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\AccountApiInterface: '@Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\AccountApi'
    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\ChampionApiInterface: '@Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\ChampionApi'
    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\LeagueApiInterface: '@Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\LeagueApi'
    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\MatchApiInterface: '@Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\MatchApi'
    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\SummonerApiInterface: '@Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\SummonerApi'
    Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\ChampionMasteryApiInterface: '@Zeggriim\RiotApiDataDragon\DataLeague\Endpoint\ChampionMasteryApi'

    # Normalizers Data Dragon
    Zeggriim\RiotApiDataDragon\DataDragon\Serializer\Normalizer\Champion\ChampionCollectionNormalizer:
        tags: [ 'serializer.normalizer' ]

    Zeggriim\RiotApiDataDragon\DataDragon\Serializer\Normalizer\LanguageCollectionNormalizer:
        tags: [ 'serializer.normalizer' ]

    Zeggriim\RiotApiDataDragon\DataDragon\Serializer\Normalizer\ProfileIcon\ProfileIconCollectionNormalizer:
        tags: [ 'serializer.normalizer' ]

    Zeggriim\RiotApiDataDragon\DataDragon\Serializer\Normalizer\ProfileIcon\ProfileIconNormalizer:
        tags: [ 'serializer.normalizer' ]

    Zeggriim\RiotApiDataDragon\DataDragon\Serializer\Normalizer\Item\ItemCollectionNormalizer:
        tags: [ 'serializer.normalizer' ]


    # Normalizers Data League
    Zeggriim\RiotApiDataDragon\DataLeague\Serializer\Normalizer\ChampionMastery\ChampionMasteryCollectionNormalizer:
        tags: [ 'serializer.normalizer' ]

    Zeggriim\RiotApiDataDragon\DataLeague\Serializer\Normalizer\ChampionMastery\ChampionMasteryNormalizer:
        tags: [ 'serializer.normalizer' ]

    Zeggriim\RiotApiDataDragon\DataLeague\Serializer\Normalizer\ChampionMastery\NextSeasonMilestonesNormalizer:
        tags: [ 'serializer.normalizer' ]

    Zeggriim\RiotApiDataDragon\DataLeague\Serializer\Normalizer\ChampionMastery\RewardConfigNormalizer:
        tags: [ 'serializer.normalizer' ]

    # Transformers Data Dragon
    Zeggriim\RiotApiDataDragon\DataDragon\Transformer\ChampionTransformer:
        arguments:
            $denormalizer: '@serializer'
