name: Security audit
on:
    pull_request:
        types: [ opened, synchronize, reopened ]

jobs:
    audit:
        name: Security audit
        runs-on: ubuntu-latest
        steps:
            -   name: checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    extensions: mbstring, xml, json, intl
                    tools: composer:v2

            -   name: Setup Cache
                run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> GITHUB_ENV

            -   name: Caching deps
                uses: actions/cache@v3
                with:
                    path: ${{ env.COMPOSER_CACHE_DIR }}
                    key: php8.3-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        php8.3-composer-latest-
                        
            -   name: Update Composer
                run: composer self-update

            -   name: Install dependencies
                run: composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

            -   name: Security audit
                run: |
                    composer audit \
                    --no-dev \
                    --abandoned="report" \
                    >> /tmp/security-audit.txt

            -   name: upload security audit report
                uses: actions/upload-artifact@v4
                if: always()
                with:
                    name: security-audit
                    path: /tmp/security-audit.txt
