name: CI

on: [push, pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-progress --no-scripts --no-interaction

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --config=../../php-cs-fixer.dist.php --dry-run --diff