name: Release Drafter (dev)

on:
    push:
        branches:
            - 3.0.0
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - 3.0.0

permissions:
    contents: read

jobs:
    update_release_draft:
        name: Update Dev Release Draft
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: release-drafter/release-drafter@v6
              with:
                  config-name: release-drafter-dev.yml
                  commitish: 3.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
